#!/bin/sh

# This part is borrowed from Luke Smith

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

printf "^c#8ec07c^󰓅 ^c#458588^󰕒^d^ %4s ^c#98971a^󰇚^d^ %4s" $(numfmt --to=iec "$tx" "$rx")


